---
name: {{ cookiecutter.project_slug }}-job-yaml-lint
{% raw %}
on:
  workflow_call:
    inputs:
      VERBOSITY:
        description: "Manages the types of Slack notifications."
        required: true
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  run_yamllint:

    runs-on: ubuntu-latest

    steps:
      - name: Yaml Lint Test -- Checkout Repository
        uses: {% endraw %}{{ cookiecutter._GITHUB_ACTION_CHECKOUT }}{% raw %}

      - name: Yaml Lint Test -- Setup Environment
        run: |
          source "./.github/scripts/workflow-setup-environment.sh"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Yaml Lint Test -- Run Linter on GitHub Workflows
        uses: {% endraw %}{{ cookiecutter._GITHUB_ACTION_YAMLLINT }}{% raw %}
        with:
          format: standard
          file_or_dir: ./.github/workflows
          config_file: ./profile/.yamllint.yml

      - name: Yaml Lint Test -- Run Linter on Top Level Configurations
        uses: {% endraw %}{{ cookiecutter._GITHUB_ACTION_YAMLLINT }}{% raw %}
        with:
          format: standard
          file_or_dir: .pre-commit-config.yaml mac_maker.yml
          config_file: ./profile/.yamllint.yml

      - name: Yaml Lint Test -- Report Job Status (Success)
        if: inputs.VERBOSITY == true
        run: |
          "./.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":white_check_mark: YAML linting was successful!"

      - name: Yaml Lint Test -- Report Job Status (Failure)
        if: failure()
        run: |
          "./.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":x: YAML linting has failed!"
{% endraw %}