---
- name: "Profile - {{cookiecutter.profile_slug}}"
  hosts: localhost
  connection: local

  handlers:
    - name: Load Handlers
      ansible.builtin.import_tasks: "handlers/main.yml"

  pre_tasks:
    - name: Load Variables
      ansible.builtin.include_vars: "vars/main.yml"

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - osx_provisioner.homebrew_retry
    - osx_provisioner.clamav
    - osx_provisioner.asdf

  post_tasks:
    - name: Run Post Install Tasks
      ansible.builtin.include_tasks: "tasks/post_install/main.yml"
