---
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: osx_provisioner.homebrew_retry
    version: v0.3.0
  - name: osx_provisioner.asdf
    version: v0.2.2
  - name: osx_provisioner.clamav
    version: v0.2.1
collections:
  - name: geerlingguy.mac
    version: 2.1.0
