---
collections:
  - name: community.general
    version: ">=6.3.0,<7.0.0"
  - name: geerlingguy.mac
    version: ">=2.1.1,<3.0.0"
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: osx_provisioner.asdf
    version: master  # Latest Production
  - name: osx_provisioner.clamav
    version: master  # Latest Production
  - name: osx_provisioner.homebrew_retry
    version: master  # Latest Production
