---
name: {{ cookiecutter.profile_slug}}-workflow-push

#  Before adding additional jobs to this workflow we encourage you examine the configuration.
#  The file: .github/config/workflows/workflow-push.json may suit your needs.

on:
  push:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

#  secrets:
#    SLACK_WEBHOOK:
#      description: "Optional, enables Slack notifications."
#      required: false

env:
  PYTHON_VERSION: "{{ cookiecutter._MAC_MAKER_PYTHON_VERSION }}"
  MAC_MAKER_PYTHON_VERSION: "{{ cookiecutter._MAC_MAKER_PYTHON_VERSION }}"

jobs:

  configuration:

    runs-on: ubuntu-latest
    outputs:
      configuration: {% raw %}${{ steps.configuration.outputs.value }}{% endraw %}
      python-version: {% raw %}${{ steps.python-version.outputs.value }}{% endraw %}

    steps:
      - name: Create Configuration -- Checkout Repository
        uses: {{ cookiecutter._GITHUB_ACTION_CHECKOUT }}

      - name: Create Configuration -- Validate the 'workflow-push.json' File
        run: |
          python -m json.tool ".github/config/workflows/workflow-push.json" >> /dev/null

      - name: Create Configuration -- Set the 'workflow-push.json' Configuration File as Output
        id: configuration
        run: |
          source ".github/scripts/workflow-set-value.sh" cat ".github/config/workflows/workflow-push.json"

      - name: Create Configuration -- Set the Mac Maker Python Version as Output
        id: python-version
        run: |
          source ".github/scripts/workflow-set-value.sh" echo "${MAC_MAKER_PYTHON_VERSION}"

  start:
    uses: ./.github/workflows/.job-00-start.yml
    secrets: inherit

  success:
    needs: [create_release]
    uses: ./.github/workflows/.job-00-success.yml
    secrets: inherit

  security_test:
    needs: [configuration]
    uses: ./.github/workflows/.job-10-security.yml
    with:
      TRUFFLEHOG_ARGS: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_trufflehog_extra_scan_args }}{% endraw %}
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit

  documentation_test:
    needs: [configuration]
    uses: ./.github/workflows/.job-30-documentation.yml
    with:
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit

  ansible_lint:
    needs: [configuration]
    uses: ./.github/workflows/.job-40-ansible-lint.yml
    with:
      PYTHON_VERSION: {% raw %}${{ needs.configuration.outputs.python-version }}{% endraw %}
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit

  commit_lint_test:
    needs: [configuration]
    uses: ./.github/workflows/.job-80-commit-lint.yml
    with:
      COMMITIZEN_REV_RANGE: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_commitzen_rev_range }}{% endraw %}
      PYTHON_VERSION: {% raw %}${{ needs.configuration.outputs.python-version }}{% endraw %}
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit

  {%- if cookiecutter.optional_toml_linting == 'true' %}

  toml_lint_test:
    needs: [configuration]
    uses: ./.github/workflows/.job-80-toml-lint.yml
    with:
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit

  {%- endif %}
  {%- if cookiecutter.optional_workflow_linting == 'true' %}

  workflow_lint_test:
    needs: [configuration]
    uses: ./.github/workflows/.job-80-workflow-lint.yml
    with:
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit

  {%- endif %}

  yaml_lint_test:
    needs: [configuration]
    uses: ./.github/workflows/.job-80-yaml-lint.yml
    with:
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit

  create_release:
    needs: [ansible_lint, commit_lint_test, configuration, documentation_test, security_test, start,{% if cookiecutter.optional_toml_linting == 'true' %} toml_lint_test,{% endif %} yaml_lint_test]
    uses: ./.github/workflows/.job-99-create-release.yml
    with:
      EXTRA_RELEASE_CONTENT: {% raw %}${{ toJSON(fromJSON(needs.configuration.outputs.configuration).ci_extra_release_content) }}{% endraw %}
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit
