---
name: profile-generator-job-remote-push

on:
  workflow_call:
    inputs:
      CONFIGURATION:
        description: "The 'cookiecutter.json' file as a configuration object."
        required: true
        type: string
    secrets:
      REMOTE_TOKEN:
        description: "GitHub token with access to the test repository."
        required: true
      REMOTE_ORIGIN:
        description: "Identifies the test repository as: owner/repository"
        required: true
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

env:
  PROFILE_GENERATOR_SKIP_POETRY: 1
  PROFILE_GENERATOR_SKIP_PRECOMMIT: 1
  TEST_PUSH_TAG: "0.1.0"

jobs:

  push_to_test_repository:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        cookiecutter-toml-selection: [1, 2]
      max-parallel: ${{ fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_CONCURRENCY }}

    steps:
      - name: Push Test -- Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'template'
          persist-credentials: false

      - name: Push Test -- Setup Environment
        run: |
          source "./template/.github/scripts/workflow-setup-environment.sh"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Push Test -- Set up Python ${{ fromJson(inputs.CONFIGURATION)._MAC_MAKER_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ fromJson(inputs.CONFIGURATION)._MAC_MAKER_PYTHON_VERSION }}

      - name: Push Test -- Install Template Requirements
        run: |
          source "./template/.github/scripts/task-template-requirements.sh"

      - name: Push Test -- Render Template
        run: |
          source "./template/.github/scripts/template.sh" "${SELECTION_TOML}" "GitHub Action" "action@github.com"
        env:
          SELECTION_TOML: ${{ matrix.cookiecutter-toml-selection }}

      - name: Push Test -- Clean Up Test Releases
        if: matrix.cookiecutter-toml-selection == 1
        run: |
          source "./template/.github/scripts/job-60-prune-test-releases.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.REMOTE_TOKEN }}
          REMOTE_ORIGIN: ${{ secrets.REMOTE_ORIGIN }}

      - name: Push Test -- Push To Test Repository (${{ env.PROFILE_GENERATOR_BRANCH_NAME_BASE }})
        if: matrix.cookiecutter-toml-selection == 1
        run: |
          source "./template/.github/scripts/job-60-test-push.sh" "${PROFILE_GENERATOR_BRANCH_NAME_BASE}"
        env:
          REMOTE_TOKEN: ${{ secrets.REMOTE_TOKEN }}
          REMOTE_ORIGIN: ${{ secrets.REMOTE_ORIGIN }}

      - name: Push Test -- Push To Test Repository (${{ env.TEST_PUSH_TAG }})
        if: matrix.cookiecutter-toml-selection == 1
        run: |
          source "./template/.github/scripts/job-60-test-push.sh" "${PROFILE_GENERATOR_BRANCH_NAME_BASE}" "${TEST_PUSH_TAG}"
        env:
          REMOTE_TOKEN: ${{ secrets.REMOTE_TOKEN }}
          REMOTE_ORIGIN: ${{ secrets.REMOTE_ORIGIN }}

      - name: Push Test -- Push To Test Repository (${{ env.PROFILE_GENERATOR_BRANCH_NAME_DEVELOPMENT }})
        if: matrix.cookiecutter-toml-selection == 2
        run: |
          source "./template/.github/scripts/job-60-test-push.sh" "${PROFILE_GENERATOR_BRANCH_NAME_DEVELOPMENT}"
        env:
          REMOTE_TOKEN: ${{ secrets.REMOTE_TOKEN }}
          REMOTE_ORIGIN: ${{ secrets.REMOTE_ORIGIN }}

      - name: Push Test -- Report Job Status on Success
        if: fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS == true
        run: |
          "./template/{{cookiecutter.profile_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":white_check_mark: remote push (${{ matrix.cookiecutter-toml-selection }}) has been triggered!"

      - name: Push Test -- Report Job Status on Failure
        if: failure()
        run: |
          "./template/{{cookiecutter.profile_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":x: remote push (${{ matrix.cookiecutter-toml-selection }}) failed to trigger!"
