---
name: profile-generator-job-create-release

on:
  workflow_call:
    inputs:
      CONFIGURATION:
        description: "The 'cookiecutter.json' file as a configuration object."
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

env:
  PROFILE_GENERATOR_SKIP_POETRY: 1
  PROFILE_GENERATOR_SKIP_PRECOMMIT: 1

jobs:

  generate_github_release:

    runs-on: ubuntu-latest

    steps:
      - name: Create Release -- Checkout Repository
        uses: actions/checkout@v3

      - name: Create Release -- Filter Release Candidates
        id: filter
        run: |
          source "./{{cookiecutter.project_slug}}/.github/scripts/job-99-release-candidate.sh" "${{ github.event.ref }}"

      - name: Create Release -- Checkout Repository (All Commits)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release -- Setup Environment
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run: |
          source "./.github/scripts/workflow-setup-environment.sh"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Create Release -- Install Poetry
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run: |
          source "./{{cookiecutter.project_slug}}/.github/scripts/task-use-poetry.sh" "install-poetry"

      - name: Create Release -- Check 'pyproject.toml' Matches Tag
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run: |
          source "./{{cookiecutter.project_slug}}/.github/scripts/job-99-version.sh"

      - name: Create Release -- Generate Changelog
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run:
          source "./{{cookiecutter.project_slug}}/.github/scripts/job-99-create-changelog.sh"

      - name: Create Release -- Generate GitHub Release Draft
        if: steps.filter.outputs.release_candidate == 'TRUE'
        id: create_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./{{cookiecutter.project_slug}}/.github/scripts/job-99-create-release.js');
            const body = process.env.CHANGE_LOG_CONTENT + "\n" + process.env.CHECK_LIST_CONTENT;
            const tag = process.env.BRANCH_OR_TAG;
            await script({ body, context, core, github, tag })
        env:
          CHECK_LIST_CONTENT: |
            ## Deployment Checklist
            - [] Ensure master points to new tag

      - name: Create Release -- Report Job Status on Success
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run: |
          "./{{cookiecutter.project_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":white_check_mark: automated release has been created!\nhttps://github.com/${USER_NAME}/${PROJECT_NAME}/releases"

      - name: Create Release -- Report Job Status on Failure
        if: failure()
        run: |
          "./{{cookiecutter.project_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":x: automated release creation has failed!"
