---
name: profile-generator-job-yaml-lint

on:
  workflow_call:
    inputs:
      CONFIGURATION:
        description: "The 'cookiecutter.json' file as a configuration object."
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

env:
  PROFILE_GENERATOR_SKIP_POETRY: 1
  PROFILE_GENERATOR_SKIP_PRECOMMIT: 1

jobs:

  run_yamllint:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        cookiecutter-toml-selection: [1, 2]
      max-parallel: ${{ fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_CONCURRENCY }}

    steps:
      - name: Yaml Lint Test -- Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'template'

      - name: Yaml Lint Test -- Setup Environment
        run: |
          source "./template/.github/scripts/workflow-setup-environment.sh"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Yaml Lint Test -- Set up Python ${{ fromJSON(inputs.CONFIGURATION)._MAC_MAKER_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ fromJSON(inputs.CONFIGURATION)._MAC_MAKER_PYTHON_VERSION }}

      - name: Yaml Lint Test-- Install Template Requirements
        run: |
          source "./template/.github/scripts/requirements.sh"

      - name: Yaml Lint Test -- Render Template
        run: |
          source "./template/.github/scripts/template.sh" "${SELECTION_TOML}"
        env:
          SELECTION_TOML: ${{ matrix.cookiecutter-toml-selection }}

      - name: Yaml Lint Test -- Lint Template GitHub Workflows
        uses: ibiqlik/action-yamllint@v3
        with:
          format: standard
          file_or_dir: ./template/.github/workflows
          config_file: ./${{ env.TEMPLATED_NAME }}/profile/.yamllint.yml

      - name: Yaml Lint Test -- Lint Rendered GitHub Workflows
        uses: ibiqlik/action-yamllint@v3
        with:
          format: standard
          file_or_dir: ./${{ env.TEMPLATED_NAME }}/.github/workflows/
          config_file: ./${{ env.TEMPLATED_NAME }}/profile/.yamllint.yml

      - name: Yaml Lint Test -- Lint Rendered Top Level Configuration Files
        uses: ibiqlik/action-yamllint@v3
        with:
          format: standard
          file_or_dir: ./${{ env.TEMPLATED_NAME }}/.pre-commit-config.yaml ./${{ env.TEMPLATED_NAME }}/mac_maker.yml
          config_file: ./${{ env.TEMPLATED_NAME }}/profile/.yamllint.yml

      - name: Yaml Lint Test -- Report Job Status on Success
        if: fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS == true
        run: |
          "./template/{{cookiecutter.profile_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":white_check_mark: YAML linting (${{ matrix.cookiecutter-toml-selection }}) checks succeeded!"

      - name: Yaml Lint Test -- Report Job Status on Failure
        if: failure()
        run: |
          "./template/{{cookiecutter.profile_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":x: YAML linting (${{ matrix.cookiecutter-toml-selection }}) checks failed!"
