---
name: profile-generator-job-workflow-lint

on:
  workflow_call:
    inputs:
      CONFIGURATION:
        description: "The 'cookiecutter.json' file as a configuration object."
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

env:
  PROFILE_GENERATOR_SKIP_POETRY: 1
  PROFILE_GENERATOR_SKIP_PRECOMMIT: 1

jobs:

  run_actionlint:

    runs-on: ubuntu-latest

    steps:
      - name: Workflow Lint -- Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'template'

      - name: Workflow Lint -- Setup Environment
        run: |
          source "./template/.github/scripts/workflow-setup-environment.sh"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Workflow Lint -- Install Binary
        run: |
          bash <(curl "${{ fromJson(inputs.CONFIGURATION)._GITHUB_CI_ACTIONLINT_SCRIPT_URL }}")

      - name: Workflow Lint -- Set up Python ${{ fromJson(inputs.CONFIGURATION)._MAC_MAKER_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ fromJson(inputs.CONFIGURATION)._MAC_MAKER_PYTHON_VERSION }}

      - name: Workflow Lint -- Install Template Requirements
        run: |
          source "./template/.github/scripts/task-template-requirements.sh"

      - name: Workflow Lint -- Render Template
        run: |
          source "./template/.github/scripts/task-render-template.sh"

      - name: Workflow Lint -- Run Linter (Template)
        run: |
          cd template
          ../actionlint -color

      - name: Workflow Lint -- Run Linter (Rendered Template)
        run: |
          cd "${TEMPLATED_NAME}"
          ../actionlint -color

      - name: Workflow Lint -- Report Job Status (Success)
        if: fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS == true
        run: |
          "./template/{{cookiecutter.project_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":white_check_mark: workflow linting was successful!"

      - name: Workflow Lint -- Report Job Status (Failure)
        if: failure()
        run: |
          "./template/{{cookiecutter.project_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":x: workflow linting has failed!"
