---
name: profile-generator-job-shell-lint

on:
  workflow_call:
    inputs:
      CONFIGURATION:
        description: "The 'cookiecutter.json' file as a configuration object."
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

env:
  PROFILE_GENERATOR_SKIP_POETRY: 1
  PROFILE_GENERATOR_SKIP_PRECOMMIT: 1

jobs:

  run_shellcheck:

    runs-on: ubuntu-latest

    steps:
      - name: Shellcheck -- Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'template'

      - name: Shellcheck -- Setup Environment
        run: |
          source "./template/.github/scripts/setup.sh"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Shellcheck -- Set up Python ${{ fromJson(inputs.CONFIGURATION)._MAC_MAKER_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ fromJson(inputs.CONFIGURATION)._MAC_MAKER_PYTHON_VERSION }}

      - name: Shellcheck -- Install Template Requirements
        run: |
          source "./template/.github/scripts/requirements.sh"

      - name: Shellcheck -- Render Template
        run: |
          source "./template/.github/scripts/template.sh"

      - name: Shellcheck -- Shellcheck Scripts
        run: |
          shellcheck ./template/hooks/*.sh
          shellcheck ./template/scripts/*.sh
          shellcheck ./template/.github/scripts/*.sh

      - name: Shellcheck -- Shellcheck Rendered Scripts
        run: |
          cd "${TEMPLATED_NAME}"
          shellcheck ./.github/scripts/*.sh
          shellcheck -x ./.pre-commit/*.sh

      - name: Shellcheck -- Report Job Status on Success
        if: fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS == true
        run: |
          "./template/{{cookiecutter.profile_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":white_check_mark: shellcheck checks succeeded!"

      - name: Shellcheck -- Report Job Status on Failure
        if: failure()
        run: |
          "./template/{{cookiecutter.profile_slug}}/.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":x: shellcheck checks failed!"
