---
name: profile-generator-self-test

# Required GitHub Repository Secrets:
# REMOTE_TOKEN      - GitHub token with access to the test repository.
# REMOTE_ORIGIN     - The git remote repository name (organization/repo).
# SLACK_WEBHOOK     - The slack webhook for build notifications.

on:
  push:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:

  _create_configuration:

    runs-on: ubuntu-latest
    outputs:
      configuration: ${{ steps.cookiecutter_configuration.outputs.value }}

    steps:
      - name: Create Configuration -- Checkout Repository
        uses: actions/checkout@v3

      - name: Create Configuration -- Set Cookiecutter Configuration as Output
        id: cookiecutter_configuration
        run: |
          source ./{{cookiecutter.profile_slug}}/.github/scripts/workflow-set-value.sh cat cookiecutter.json

  _start_notification:

    runs-on: ubuntu-latest

    steps:
      - name: Start -- Checkout Repository
        uses: actions/checkout@v3

      - name: Start -- Setup Environment
        run: |
          source ./.github/scripts/setup.sh
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Start -- Report Job Status on Success
        run: |
          ./{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":white_check_mark: workflow has started!"

      - name: Start -- Report Job Status on Failure
        if: failure()
        run: |
          ./{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":x: error reporting job status!"

  _success_notification:
    needs: [create_release]

    runs-on: ubuntu-latest

    steps:
      - name: Success -- Checkout Repository
        uses: actions/checkout@v3

      - name: Success -- Setup Environment
        run: |
          source ./.github/scripts/setup.sh
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Success -- Report Job Status on Success
        run: |
          ./{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":white_check_mark: all checks were successful!"

      - name: Success -- Report Job Status on Failure
        if: failure()
        run: |
          ./{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":x: error reporting job status!"

  ansible_lint_test:
    needs: [_create_configuration]

    runs-on: ubuntu-latest
    env:
      PROFILE_GENERATOR_SKIP_POETRY: 0
      PROFILE_GENERATOR_SKIP_PRECOMMIT: 0
      SELECTION_TOML: 1

    steps:

      - name: Ansible Lint -- Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'template'

      - name: Ansible Lint -- Setup Environment
        run: |
          source ./template/.github/scripts/setup.sh
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Ansible Lint -- Set up Python ${{ fromJson(needs._create_configuration.outputs.configuration)._MAC_MAKER_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ fromJson(needs._create_configuration.outputs.configuration)._MAC_MAKER_PYTHON_VERSION }}

      - name: Ansible Lint -- Install Template Requirements
        run: |
          source ./template/.github/scripts/requirements.sh

      - name: Ansible Lint -- Initialize Cache Locations
        run: |
          mkdir -p ~/.cache/pypoetry/virtualenvs
          source ./template/{{cookiecutter.profile_slug}}/.github/scripts/ansible_cache.sh  \
            "$(pwd)/ansible_cache"                                                          \
            ~/.ansible

      - name: Ansible Lint -- Mount Ansible Cache
        uses: actions/cache@v3
        with:
          key: ansible-${{ hashFiles('./template/{{cookiecutter.profile_slug}}/profile/requirements.yml') }}-${{ env.CACHE_TTL }}
          path: ansible_cache

      - name: Ansible Lint -- Mount Poetry Cache
        uses: actions/cache@v3
        with:
          key: poetry-${{ hashFiles('./template/{{cookiecutter.profile_slug}}/pyproject.toml') }}-${{ runner.os }}-${{ env.CACHE_TTL }}
          path: ~/.cache/pypoetry/virtualenvs

      - name: Ansible Lint -- Render Template
        run: |
          source ./template/.github/scripts/template.sh

      - name: Ansible Lint -- Lint Rendered Template
        run: |
          cd "${TEMPLATED_NAME}/profile"
          poetry run ansible-lint

      - name: Ansible Lint -- Report Job Status on Success
        if: fromJSON(needs._create_configuration.outputs.configuration)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS == true
        run: |
          ./template/{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":white_check_mark: ansible linting checks succeeded!"

      - name: Ansible Lint -- Report Job Status on Failure
        if: failure()
        run: |
          ./template/{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":x: ansible linting checks failed!"

  apply_profile_test:
    needs: [_create_configuration, push_repository_test]

    runs-on: macos-${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [12]
        platform: [x86_64]

    steps:
      - name: Apply Profile -- Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'template'

      - name: Apply Profile -- Setup Environment
        run: |
          source ./template/.github/scripts/setup.sh
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Apply Profile -- Initialize Cache Locations
        run: |
          source ./template/{{cookiecutter.profile_slug}}/.github/scripts/ansible_cache.sh  \
            "$(pwd)/ansible_cache"                                                          \
            "$(pwd)/installer.workspace/${TEMPLATED_NAME}-${PROFILE_GENERATOR_BRANCH_NAME_BASE}/profile"

      - name: Apply Profile -- Mount Ansible Cache
        uses: actions/cache@v3
        with:
          key: ansible-${{ hashFiles('./template/{{cookiecutter.profile_slug}}/profile/requirements.yml') }}-${{ env.CACHE_TTL }}
          path: ansible_cache

      - name: Apply Profile -- Apply Pushed Profile
        run: |
          source ./template/.github/scripts/apply.sh
        env:
          MAC_MAKER_VERSION: ${{ fromJson(needs._create_configuration.outputs.configuration)._MAC_MAKER_MIN_VERSION }}
          OS_VERSION: ${{ matrix.os }}
          PLATFORM_VERSION: ${{ matrix.platform }}

      - name: Apply Profile -- Report Job Status (Success)
        if: fromJSON(needs._create_configuration.outputs.configuration)._GITHUB_CI_DEFAULT_VERBOSE_NOTIFICATIONS == true
        run: |
          ./template/{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":white_check_mark: OSX ${{ matrix.os }}, profile application was successful"

      - name: OSX Build -- Report Job Status (Failure)
        if: failure()
        run: |
          ./template/{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":x: OSX ${{ matrix.os }}, profile application failed!"

  create_release:
    needs: [apply_profile_test]

    runs-on: ubuntu-latest

    steps:
      - name: Create Release -- Checkout Repository
        uses: actions/checkout@v3

      - name: Create Release -- Filter Release Candidates
        id: filter
        run: |
          source ./{{cookiecutter.profile_slug}}/.github/scripts/release-candidate.sh "${{ github.event.ref }}"

      - name: Create Release -- Checkout Repository (All Commits)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release -- Setup Environment
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run: |
          source ./.github/scripts/setup.sh
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Create Release -- Install Poetry
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run: |
          source ./{{cookiecutter.profile_slug}}/.github/scripts/poetry.sh "install-poetry"

      - name: Create Release -- Check 'pyproject.toml' Matches Tag
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run: |
          source ./{{cookiecutter.profile_slug}}/.github/scripts/version.sh

      - name: Create Release -- Generate Changelog
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run:
          source ./{{cookiecutter.profile_slug}}/.github/scripts/changelog.sh

      - name: Create Release -- Generate GitHub Release Draft
        if: steps.filter.outputs.release_candidate == 'TRUE'
        id: create_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./{{cookiecutter.profile_slug}}/.github/scripts/release.js');
            const body = process.env.CHANGE_LOG_CONTENT + "\n" + process.env.CHECK_LIST_CONTENT;
            const tag = process.env.BRANCH_OR_TAG;
            await script({ body, context, core, github, tag })
        env:
          CHECK_LIST_CONTENT: |
            ## Deployment Checklist
            - [] Ensure master points to new tag

      - name: Create Release -- Report Job Status on Success
        if: steps.filter.outputs.release_candidate == 'TRUE'
        run: |
          ./{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":white_check_mark: automated release has been created!\nhttps://github.com/${USER_NAME}/${PROJECT_NAME}/releases"

      - name: Create Release -- Report Job Status on Failure
        if: failure()
        run: |
          ./{{cookiecutter.profile_slug}}/.github/scripts/notifications.sh "${NOTIFICATION}" ":x: automated release creation has failed!"

  documentation_test:
    needs: [_create_configuration]
    uses: ./.github/workflows/.job-30-documentation.yml
    with:
      CONFIGURATION: ${{ needs._create_configuration.outputs.configuration }}
    secrets: inherit

  security_test_repo:
    needs: [_create_configuration]
    uses: ./.github/workflows/.job-10-security.yml
    with:
      CONFIGURATION: ${{ needs._create_configuration.outputs.configuration }}
    secrets: inherit

  precommit_test:
    needs: [_create_configuration]
    uses: ./.github/workflows/.job-50-precommit.yml
    with:
      CONFIGURATION: ${{ needs._create_configuration.outputs.configuration }}
    secrets: inherit

  push_repository_test:
    needs: [_create_configuration, _start_notification, ansible_lint_test, commit_lint_test, documentation_test, precommit_test, security_test_repo, shellcheck_test, toml_lint_test, yaml_lint_test]
    uses: ./.github/workflows/.job-60-remote-push.yml
    with:
      CONFIGURATION: ${{ needs._create_configuration.outputs.configuration }}
    secrets: inherit

  commit_lint_test:
    needs: [_create_configuration]
    uses: ./.github/workflows/.job-80-commit-lint.yml
    with:
      CONFIGURATION: ${{ needs._create_configuration.outputs.configuration }}
    secrets: inherit

  shellcheck_test:
    needs: [_create_configuration]
    uses: ./.github/workflows/.job-80-shell-lint.yml
    with:
      CONFIGURATION: ${{ needs._create_configuration.outputs.configuration }}
    secrets: inherit

  toml_lint_test:
    needs: [_create_configuration]
    uses: ./.github/workflows/.job-80-toml-lint.yml
    with:
      CONFIGURATION: ${{ needs._create_configuration.outputs.configuration }}
    secrets: inherit

  yaml_lint_test:
    needs: [_create_configuration]
    uses: ./.github/workflows/.job-80-yaml-lint.yml
    with:
      CONFIGURATION: ${{ needs._create_configuration.outputs.configuration }}
    secrets: inherit
